(module f (provide [f (int? (int? . -> . any) . -> . any)])
  (define (f x g) (g (+ x 1))))
(module h (provide [h ((and/c int? (>/c 0)) . -> . any)])
  (define (h y) 'unit))
(module main (provide [main (int? . -> . any)])
  (require f h)
  (define (main n)
    (if (> n 0) (f n h) 'unit)))

(require main)
(main •)